### ISSUE TITLE
Make Contact details Mandatory

### ISSUE THREAD

**Issue by ssmittal** [ladybirdweb/agorainvoicing#115]
Please do make contact details mandatory @vijaysebastian

**Comment by ssmittal** [comment]
Please do put download as csv option where all the details of client will come in excel sheet. @vijaysebastian

**Comment by bhanu2217** [comment]
- Make the mobile number mandatory.
- Accept numbers online in mobile field
- Put a dropdown list in front of mobile number similar to this https://premium.wpmudev.org/forums/?bb_attachments=871504&bbat=63897&inline for country code. Select the country code automatically using Geoip
