### ISSUE TITLE
OTP Verification

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agorainvoicing#136]
Implement OTP verification either via SMS or Voice. Give option to user to choose whether they want to receive call or SMS.

Looking at this API service https://2factor.in/v3/bulk-sms-pricing

**Comment by bhanu2217** [comment]
This service supports SMS OTP for international. Voice is only for India
https://2factor.in/v3/bulk-sms-pricing

**Comment by bhanu2217** [comment]
After the phone verification is completed. Email validation is still pending. Display following message.

Thank You!
You will receive an email from us shortly to verify your account.

**Comment by bhanu2217** [comment]
- https://msg91.com Provide SMS OTP only. In case someone clicks on resend OTP, than they give voice option but first time by default its SMS
- Another company to explore. www.telesign.com Pricing is not listed on website. Have emailed them for pricing

**Comment by ashu555** [comment]
Email and OTP verification mandatory when the user registers.
