### ISSUE TITLE
Swift_TransportException in POST /auth/register

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agorainvoicing#666]
## Error in Agora Invoicing

**Swift_TransportException** in **POST /auth/register**
Failed to authenticate on SMTP server with username "support@ladybirdweb.com" using 3 possible authenticators. Authenticator LOGIN returned Swift_TransportException: Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials p4sm8865613wrs.74 - gsmtp
" in /home/faveo/public_html/billing/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:456
Stack trace:
#0 /home/faveo/public_html/billing/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(343): Swift_Transport_AbstractSmtpTransport->assertResponseCode('535-5.7.8 Usern...', Array)
#1 /home/faveo/public_html/billing/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('TGFkeWJpcmQxMjN...', Array, Array, false, NULL)
#2 /home/faveo/public_html/billing/vendor/swift...

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/agora-invoicing/errors/5c0ed05b63933c001944ad52?event_id=5c0ed05b0031f1c3c9230000&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/Common/TemplateController.php:299 - App\Http\Controllers\Common\TemplateController::mailing
    app/Http/Middleware/RedirectIfAuthenticated.php:25 - App\Http\Middleware\RedirectIfAuthenticated::handle
    app/Http/Middleware/Install.php:26 - App\Http\Middleware\Install::handle

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/agora-invoicing/errors/5c0ed05b63933c001944ad52?event_id=5c0ed05b0031f1c3c9230000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Codingjames** [comment]
@ashu555 How to solve this issue please help.
Failed to authenticate on SMTP server with username "my@email.com" using 2 possible authenticators. Authenticator LOGIN returned Swift_TransportException: Expected response code 235 but got code "535",
