### ISSUE TITLE
Settings -> System setting error validation does not remember previously set values

### ISSUE THREAD

**Issue by juanluisbaptiste** [ladybirdweb/agorainvoicing#761]
Hi,

On Settings -> System setting (at least, haven't seen it yet in other place) when there's a wrong or empty value and the Update button is clicked and the page is reloaded showing the submit errors, the previous set form values are gone and need to be set again. IMO after an error what you had already filled should be remembered when an error occurs and the page is reloaded.

**Comment by ashu555** [comment]
All issues i the system such as these will be fixed in the next release
