### ISSUE TITLE
Close button in Add plugin box with no skin

### ISSUE THREAD

**Issue by juanluisbaptiste** [ladybirdweb/agorainvoicing#762]
Hi,

when clicking on the _Add New_ button on the Plugins page, the add plugin dialog is missing the skin on the close button:

![Screenshot_20190316_130119](https://user-images.githubusercontent.com/2113585/54479523-98536680-47eb-11e9-9fc4-6c76b91bcdca.png)

**Comment by ashu555** [comment]
Fixed In Latest Release

**Comment by ashu555** [comment]
Fixed In Latest Release
