### ISSUE TITLE
Retry OTP Page needs to be improved

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agorainvoicing#767]
- UI needs to be improved
- Retry Msg91 API needs to be implemented
- Component needs to be converted to Vue

**Comment by ashu555** [comment]
@bhanu2217  This issue is fixed. However, the page is still not converted to vue. Can we close this issue and  link conversion to  vue into other milestone?

**Comment by bhanu2217** [comment]
Sounds good. We don't need Vue for now
